
apiVersion: v1
kind: Service
metadata:
  name: rolling-update-service
  namespace: rolling-ns
spec:
  selector:
    app: simple-website
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      